print("Fatih Sultan Mehmed")
print("Kanuni Sultan Süleyman")
print("Osman Gazi")
print("İsmet İnönü")
print("Mustafa Kemal Atatürk")
print("Recep Tayyip Erdoğan")
print("Tuğrul")
print("Sultan Alparslan")
print("III.Selim")
print("Yıldırım Beyazıd")
