print("Vlademir Putin")
print("Donald Trump")
print("Macron")
print("Friedrich Merz")
print("Recep Tayyip Erdoğan")
print("Vezir-i Azam")
print("Xi Jinping")
print("Papa")
print("Kim Jong-un")
print("Yoon Suk Yeol")
print("Alexander Van der Bellen")
print("Orban")
print("Xavier Bettel")
print("Bart De Wever")